[package]
name = "missing-compass"
version = "0.1.0"
authors = ["James Healy <james@yob.id.au>"]
edition = "2018"

[dependencies]
serde = "1.0.89"
serde_derive = "1.0.89"
reqwest = "0.9.12"
clap = "2.33.0"
