#! /bin/bash -eu
#
# Operate in environment suitable for running ruby

cd $(dirname $0)/..

docker volume create missing-compass-gems > /dev/null

docker run \
  -v `pwd`:/work:rw \
  --mount source=missing-compass-gems,target=/usr/local/bundle  \
  -w /work \
  --entrypoint /work/scripts/bundle-exec \
  --rm \
  -t ruby:3.3.5 \
  "${@-bash}" # default command to launch in the container
